### ISSUE TITLE
Considerar dispositivos que hacen mediciones por pares (ejemplo bluetooth)

### ISSUE THREAD

**Issue by ednaru** [CiudadesAbiertas/vocab-transporte-trafico#11]
Se tienen casos de dispositivos pueden hacer mediciones por pares, tal es el caso de dispositivos bluetooth que pueden hacer mediciones al principio y final de un tramo.
La cardinalidad de la propiedad madeBySensor entre Observacion y EquipoMedicionTrafico es ahora (1:n), es decir que si por ejemplo se ha calculado la velocidad media en el tramo, esa observación estaría asociada mediante madeBySensor a dos sensores. Se añade  según reunión con Ayuntamientos del 02/06/2020.

**Comment by flowsta** [comment]
Al abordar estos sensores había dos cuestiones con respecto a la representación que habíamos iniciado a hacer:
1. Son sensores lógicos compuestos de dos sensores físicos;
2. ¿Qué ubicación tienen los sensores físicos?

Pregunta realizada a experto de tráfico:

> En el caso de los dispositivos Bluetooth hay dos en un tramo que miden la velocidad media entre los detectores. La pregunta es si conviene representar que son dos dispositivos que producen dos observaciones y una observación calculada, qué dispositivo lo produce; si los consideramos un dispositivo solo que produce una observación, la calculada.
> 
> El hecho de que sea en un punto en un tramo, tal como se diseñó el vocabulario, no afecta en cuanto la observación ya que contempla que lo que está haciendo actualmente, sacar el resultado de un tramo.
> 
> ¿Sería este comportamiento similar a un "radar de tramo"?
> 

La respuesta:

> Se podría considerar la medición del tramo como una, asociada a un par de detectores. Es decir un dispositivo es un par de detectores que mide la velocidad de un tramo.
> Luego el comportamiento es similar a un radar de tramo

Según esto, pondría en `rdfs:comments` que esos dispositivos, el bluetooth y el radar de tramo, tienen dos detectores que envían las mediciones y el dispositivo saca una medición. La ubicación sería, por tanto, la de la medición.

**Comment by flowsta** [comment]
Dado que [madeBySensor](https://www.w3.org/TR/vocab-ssn/#SOSAmadeBySensor) no tiene restricciones de cardinalidad, una observacion puede estar asociada a un par de sensores.

En estos casos la observación es la velocidad media.
