### ISSUE TITLE
Añadir propiedad estraf:validada a la Observación

### ISSUE THREAD

**Issue by ednaru** [CiudadesAbiertas/vocab-transporte-trafico#12]
Se añade propiedad booleana validada para indicar si la observación ha sido validada o no. Se añade  según reunión con Ayuntamientos del 02/06/2020.

**Comment by flowsta** [comment]
También se añade a Observacion la propiedad `dct:id`, quedando así:

- `dct:identifier (1..1) :: xsd:string`
- ` sosa:resultTime (1..1) :: xsd:dateTime`
- `sosa:hasSimpleResult (1..1)`
- `estraf:validada (1..1) :: xsd:boolean`

**Comment by flowsta** [comment]
Tal como se quedó en la reunión, con respecto a la curación de datos:

> Se puede hacer curación de datos y modificar datos del pasado, por errores, por ejemplo, ya que pueden tener un 5% de sensores fuera de línea por lo que se pueden hacer correcciones; o para los datos de contaminación atmosférica.

Se acordó por tanto añadir un concepto validado (o no) como verdadero o falso,

**Comment by ednaru** [comment]
En la reunión del 02/06/2020 se comentó que se puede hacer curación de datos y modificar datos del pasado, por errores, por ejemplo. Madrid comentó que solo publican datos no validados pero para su gestión interna sí publican datos validados ya que pueden tener por ejemplo un 5% de sensores fuera de línea por lo que se pueden hacer correcciones. UPM comentó que se puede añadir un concepto validado (o no) como verdadero o falso, sobretodo para históricos. Zaragoza comentó que está ese valor para contaminación atmosférica porque los datos se deben corregir.
