### ISSUE TITLE
Verificar atributos estraf:enServicio y estraf:frecuenciaMedicion

### ISSUE THREAD

**Issue by ednaru** [CiudadesAbiertas/vocab-transporte-trafico#13]
Issue de @hlafuente "Para estraf:DispositivoMedicionTrafico el diagrama dice que tiene los atributos enServicio y  frecuenciaMedicion pero en el owl no aparecen. ¿Son atributos de  estraf:DispositivoMedicionTrafico ?"

El atributo estraf:enServicio se agrega a la ontología
El atributo estraf:frecuenciaMedicion se agrega a la ontología.

**Comment by flowsta** [comment]
Ya están publicados en el repositorio
