### ISSUE TITLE
Definir cardinalidad de relación entre Tramo e Incidencia

### ISSUE THREAD

**Issue by ednaru** [CiudadesAbiertas/vocab-transporte-trafico#14]
Introducido por @hlafuente . La relación entre Incidencia y Tramo es 0:1 (se corrige pues  estaba definido como 0:n) y entre Tramo y Vía es (0:n), es decir 1 Incidencia está asociada a 1 Tramo.

**Comment by flowsta** [comment]
La diferencia proviene de ¿qué es un Tramo? Si contemplas un Tramo de una incidencia como único, con un principio y un fin por definir, o si una Incidencia puede tener varios Tramos con principios y fines correspondientes a viales o Tramos de Vía.
