### ISSUE TITLE
Modificar relación sosa:madeBySensor 

### ISSUE THREAD

**Issue by ednaru** [CiudadesAbiertas/vocab-transporte-trafico#15]
En diagrama, Figura 2 de la documentación, el sosa:madeBySensor entre sosa:Observation y sosa:EquipoTrafico, debe ser entre sosa:Observation y sosa:Sensor.

**Comment by flowsta** [comment]
https://github.com/CiudadesAbiertas/vocab-transporte-trafico/commit/4567347e8aa5de0bb665de7382ac8c2831421953
