### ISSUE TITLE
Modificar time:inXSDgYearMonth por time:inXSDDateTimeStamp

### ISSUE THREAD

**Issue by ednaru** [CiudadesAbiertas/vocab-transporte-trafico#16]
En time:Instant modificar atributo a time:inXSDDateTimeStamp dado que se manejan intervalos de tiempo delimitados por timestamp.

**Comment by flowsta** [comment]
https://github.com/CiudadesAbiertas/vocab-transporte-trafico/commit/4567347e8aa5de0bb665de7382ac8c2831421953

**Comment by flowsta** [comment]
https://github.com/CiudadesAbiertas/vocab-transporte-trafico/commit/ae04b6e58357f96978e9fb888e47deacc136a430
