### ISSUE TITLE
Definición de niveles de densidad de tráfico

### ISSUE THREAD

**Issue by paoespinozarias** [CiudadesAbiertas/vocab-transporte-trafico#3]
Se realiza la siguiente propuesta inicial de [niveles](https://github.com/CiudadesAbiertas/vocab-transporte-trafico/files/3241840/Niveles.de.Densidad.de.Trafico.xlsx)

**Comment by flowsta** [comment]
Definidos los niveles, se resuelve en las incidencias #10 y #9
