### ISSUE TITLE
`estraf:incidenciaAdjunto` para `estraf:Incidencia`

### ISSUE THREAD

**Issue by flowsta** [CiudadesAbiertas/vocab-transporte-trafico#5]
Al relacionar una esautob:Linea con una estraf:incidencia se los adjuntos (PDF) en urls de las incidencias de autobús de EMT.
Podría hacerse la propiedad `estraf:incidenciaAdjunto`:
`<http://vocab.ciudadesabiertas.es/recurso/transporte/trafico/incidencia/1234546> estraf:incidenciaAdjunto "http://feeds.emtmadrid.es:8082/docs/20200227-Carnavales-Distritos-2020.pdf"^^xsd:anyURI .`

**Comment by ocorcho** [comment]
Al tratarse de una simple referencia a la URL del documento, mi recomendación es reutilizar rdfs:seeAlso

**Comment by flowsta** [comment]
Ok, lo pongo así:
```
rdfs:seeAlso (0..1) :: xsd:anyURI
```
