### ISSUE TITLE
Fecha de creación de la incidencia

### ISSUE THREAD

**Issue by flowsta** [CiudadesAbiertas/vocab-transporte-trafico#6]
En `estraf:Incidencia` no está contemplada la fecha de creación de la incidencia pero en las incidencias de EMT sí. Dado que usamos esta clase para las incidencias de las líneas de autobús, valorar si conviene poner una DP `schema:dateCreated` en la clase, adaptarla o no.

**Comment by ocorcho** [comment]
Mi recomendación es utilizar dc:created, dado que es aplicable a cualquier tipo de objeto digital, en lugar de schema:dateCreated, que se aplica a schema:CreativeWork o schema:DataFeed.

**Comment by flowsta** [comment]
Ok, así lo pongo:
``
dc:created (0..1) :: xsd:dateTime
``
