### ISSUE TITLE
estraf:numSentidos y estraf:numCarriles en estraf:EquipoTrafico

### ISSUE THREAD

**Issue by hlafuente** [CiudadesAbiertas/vocab-transporte-trafico#7]
Buenos días,

En el diagrama se puede ver como estraf:numSentidos y estraf:numCarriles son atributos de estraf:EquipoTrafico pero luego en trafico.owl no se ve reflejado.

Un saludo.

**Comment by ednaru** [comment]
Las dos propiedades están en la ontología pero tienen como Domain únicamente a Incidencia.

**Comment by flowsta** [comment]
Lo cambio en la ontología y lo publicamos en la próxima versión (it's coming!)
