### ISSUE TITLE
Revisar uso de patrón de geo, geosparql, coordenadas ETRS89

### ISSUE THREAD

**Issue by ednaru** [CiudadesAbiertas/vocab-transporte-trafico#8]
- Las clases Incidencia, EquipoTrafico ahora son subclases de geosparql:Feature (Ya Tramo era subclase de geosparql:Feature.
- La clase geo:Point es ahora sf:Point con las coordenadas geo:lat y geo::long y las coordenadas geo_core:xETRS89 y geo_core:yETRS89. Se añade  según reunión con Ayuntamientos del 02/06/2020.
- Al relacionar geosparql:Feature con  geosparql:Geometry y tener sf:Point como subclase de geosparql:Geometry, se eliminan las propiedades ubicacionEquipo y ubicacionIncidencia.

**Comment by flowsta** [comment]
También determinamos utilizar el tipo de dato xsd:float, que está definido en geo_core para xETRS89 e yETRS89, para geo:lat y geo:long. Antes usábamos xsd:double. Queda así:
> geo:lat (1..1) :: xsd:float
geo:long (1..1) :: xsd:float
geo_core:xETRS89 (1..1) :: xsd:float
geo_core:yETRS89 (1..1) :: xsd:float



*Nota*: el rango para `geo:lat` y `geo:long` fue introducido en WSG84 en la Revision 1.8  2003/01/11 11:05:02 por danbri: added an rdfs:range for each lat/long/alt property, http://www.w3.org/2001/XMLSchema#float

**Comment by flowsta** [comment]
`geo:lat (1..1) :: xsd:double
geo:long (1..1) :: xsd:double
geo_core:xETRS89 (1..1) :: xsd:float
geo_core:yETRS89 (1..1) :: xsd:float
`
