### ISSUE TITLE
Agregar nuevas instancias a la clase PropiedadMedicionTrafico

### ISSUE THREAD

**Issue by ednaru** [CiudadesAbiertas/vocab-transporte-trafico#9]
Agregar instancias como velocidad y nivel de servicio. Se añade  según reunión con Ayuntamientos del 02/06/2020.

**Comment by flowsta** [comment]
Las instancias añadidas a las actuales `intensidad`, `ocupacion` y `carga`son:
- `composicion`
- `velocidad`
- `nivel`.

Nivel antes estaba como skos (ver #10)

Se comentan las propiedades que tienen según reunión con los ayuntamientos 2020-06-02
